#!/bin/bash
errors_terminate=$2

compileall_flags="$4"

# If using normal root, avoid changing anything.
if [[ -z "$RPM_BUILD_ROOT" ]] || [[ "$RPM_BUILD_ROOT" = "/" ]]; then
	exit 0
fi

# This function now implements Python byte-compilation.
# It uses the compileall module from the standard library.
function python_bytecompile()
{
    local python_binary=$1
    local python_libdir="$2"
    local compileall_flags="$3"

    # PYTHONPATH is needed for compileall2, but doesn't hurt for the stdlib
    # -o 0 -o 1 are the optimization levels
    # -q disables verbose output
    # -f forces the process to overwrite existing compiled files
    # -e excludes symbolic links pointing outside the build root
    # -s strips $RPM_BUILD_ROOT from the path
    # -p prepends the leading slash to the path to make it absolute
    # --invalidation-mode=timestamp forces the TIMESTAMP invalidation mode
    PYTHONPATH=/usr/lib/rpm/openruyi/ $python_binary -B -m compileall $compileall_flags -o 0 -o 1 -q -f -s "$RPM_BUILD_ROOT" -p / --hardlink-dupes --invalidation-mode=timestamp -e "$RPM_BUILD_ROOT" "$python_libdir"
}

# .pyc/.pyo files embed a "magic" value, identifying the ABI version of Python
# bytecode that they are for.
#
# The files below RPM_BUILD_ROOT could be targeting multiple versions of
# python (e.g. a single build that emits several subpackages e.g. a
# python26-foo subpackage, a python31-foo subpackage etc)
#
# Support this by assuming that below each /usr/lib/python$VERSION/, all
# .pyc/.pyo files are to be compiled for /usr/bin/python$VERSION.
#
# For example, below /usr/lib/python2.6/, we're targeting /usr/bin/python2.6
# and below /usr/lib/python3.1/, we're targeting /usr/bin/python3.1

shopt -s nullglob
find "$RPM_BUILD_ROOT" -type d -print0|grep -z -E "/(usr|app)/lib(64)?/python[0-9]\.[0-9]+$" | while read -d "" python_libdir;
do
	python_binary=$(basename "$python_libdir")
	echo "Bytecompiling .py files below $python_libdir using $python_binary"

	# Generate byte-compiled files.
	python_bytecompile "$python_binary" "$python_libdir" "$compileall_flags"
	if [[ $? -ne 0 ]] && [[ 0"$errors_terminate" -ne 0 ]]; then
		# One or more of the files had a syntax error
		exit 1
	fi
done
